### ISSUE TITLE
1.21 Update

### ISSUE THREAD

**Issue by ekul6547** [Nincodedo/Banners4BM#4]
Are you going to update this for 1.21?

**Comment by Nincodedo** [comment]
No, I don't have any plans to update this to 1.21. I do not have the time to work on it. I will accept PRs that update it.

**Comment by ekul6547** [comment]
> No, I don't have any plans to update this to 1.21. I do not have the time to work on it. I will accept PRs that update it.

Ok, PR created: https://github.com/Nincodedo/Banners4BM/pull/5
